### ISSUE TITLE
Error in checkout of Virtual Product

### ISSUE THREAD

**Issue by dcruz11** [experius/Magento-2-Module-Experius-ExtraCheckoutAddressFieldsTest#4]
I created a field to Addresses named "Friendly Name Address" (this is required). I can order correctly simple products.
However when I order a Virtual Product, I get an error like "setFriendlyNameAddress doesn't exists". The step is Review & Payment in payment.js. When I click to "place order" button I get the error in php log. 
You can see the trace below:

PHP Fatal error:  Uncaught Error: Call to a member function setFriendlyNameAddress() on null in /app/code/Company/ExtraCheckoutAddressFields/Helper/Data.php:49
Stack trace:
#0 /app/code/Company/ExtraCheckoutAddressFields/Observer/Sales/ModelServiceQuoteSubmitBefore.php(50): Company\ExtraCheckoutAddressFields\Helper\Data->transportFieldsFromExtensionAttributesToObject(Object(Magento\Quote\Model\Quote\Address), NULL, 'extra_checkout_...')
#1 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Company\ExtraCheckoutAddressFields\Observer\Sales\ModelServiceQuoteSubmitBefore->execute(Object(Magento\Framework\Event\Observer))
#2 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Company\ExtraCheckoutAddressFields\Observer\Sales\ModelServiceQuoteSub in /app/code/Company/ExtraCheckoutAddressFields/Helper/Data.php on line 49

Please, help me.
Thanks.

**Comment by dcruz11** [comment]
I solved it. I had to check in _sales_model_service_quote_submit_before_ observer if ShippingAddress of order is equal to null. In that case, you haven't to inicialize the extra address attributes.

**Comment by ghost** [comment]
@dcruz11 Would be nice if you could send me the code adjustments for 
https://github.com/experius/Magento-2-Module-Experius-ExtraCheckoutAddressFields/blob/master/Observer/Sales/ModelServiceQuoteSubmitBefore.php
And i will add it to the module.

**Comment by dcruz11** [comment]
The easier way is just adding

```
> if ( $order->getShippingAddress() != null ) {
> 	        $this->helper->transportFieldsFromExtensionAttributesToObject($quote->getShippingAddress(),
>         		$order->getShippingAddress(),
>         		'extra_checkout_shipping_address_fields'
> 	        );
> 	   }
```
